apiVersion: apps/v1
kind: Deployment
metadata: { name: platform-demo }
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: platform-demo } }
  template:
    metadata: { labels: { app: platform-demo } }
    spec:
      securityContext: { runAsNonRoot: true, runAsUser: 101 }
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 80 }]
          resources: {{ toYaml .Values.resources | nindent 12 }}
          readinessProbe: { httpGet: { path: /, port: 80 }, initialDelaySeconds: 5 }
          livenessProbe: { httpGet: { path: /, port: 80 }, initialDelaySeconds: 15 }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: ["ALL"] } }
---
apiVersion: v1
kind: Service
metadata: { name: platform-demo }
spec:
  selector: { app: platform-demo }
  ports: [{ port: 80, targetPort: 80 }]
